config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/', to: 'users#import'
  get '/users', to: 'users#index', as: 'users'
  post 'import_csv', to: 'users#import_csv', as: 'import_csv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log_import_file.rb
class LogImportFile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  IMPORT_HEADER_FORMAT = %i(username level).freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/get_data_csv.rb
require 'active_support/concern'
require 'csv'

module GetDataCsv
  extend ActiveSupport::Concern

  private

  def get_data_csv(file:)
    csv_text = File.read(file)
    CSV.parse(csv_text, :headers => true, header_converters: :symbol).map(&:to_h)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include GetDataCsv

  def index
    @users = User.all.order(level: :desc).paginate(page: params[:page], per_page: 10)
  end

  def import_csv
    csv = get_data_csv(file: params.require(:user).permit(:user_file)[:user_file])
    raise "Column not match" unless User::IMPORT_HEADER_FORMAT.eql? csv.first.keys

    csv.each do |row|
      User.create(row)
    end

    redirect_to users_path, flash: {success: "Import successfully"}
  rescue => e
    redirect_to '/', flash: {errors: e}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title RubyImportCsv
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .app-container
      = render "shared/navigation"

app/views/shared/_navigation.slim
.container-fluid
  .searchbox-wrapper
    .row.align-items-center
      .col-6
      ul.nav.flex-column
        li.nav-item
        = link_to '/', class: "nav-link h2 m-0 font-weight-bold ml-2 mt-3" do
          span.text-dark IMPORT CSV
  .row
    nav#sidebarMenu.col-md-3.col-sm-4.col-lg-2.d-md-block.sidebar.sidebar-wrapper
      .sidebar-sticky.pt-3
        ul.nav.flex-column
          li.nav-item
          = link_to users_path, class: "nav-link h2 m-0 font-weight-bold ml-2 mt-3" do
            span.text-white = t("dashboard.navbar.user_list")
    main.col-md-9.ml-sm-auto.col-sm-8.col-lg-10.no-padding role="main"
      = yield

app/views/users/_user.slim
tr
  td scope = "col"
    = user&.id
  td scope = "col"
    = user&.username
  td scope = "col"
    = user&.level

app/views/users/import.slim
.container.team-detail
  .row.justify-content-center
    .col-8.text-center.p-0.mt-3.mb-2
    .col-8
      - flash.each do |key, value|
        - class_name = key == success ? 'success' : 'danger'
        = content_tag :div, key, class: "flash alert alert-primary #{value}"
      .card.px-4.pt-4.pb-0.mt-3.mb-3
        .row
          .col-12.justify-content-start.d-flex.pr-0
            h2.mb-0 = "Import CSV"
        hr
        .row
          .col-12.justify-content-start.d-flex.pr-0
            = form_for :user, :url => import_csv_path do |f|
              .row.justify-content-center
                .form-group
                  .col-12.form-control
                    = f.file_field :user_file, accept: '.csv'
                  .form-group
                    .col-12
                      = f.label :file_description, "Supported file format only .csv"
                .form-group
                  .col-3
                    = f.submit "Import", name: "Import", class: "btn btn-primary", style: "float: left;"

app/views/users/index.slim
.container.mb-3
  .row.justify-content-center
    .col-8.text-center.p-0.mt-3.mb-2
    .col-8
      - flash.each do |key, value|
        - class_name = key == 'success' ? 'success' : 'danger'
        = content_tag :div, key, class: "flash alert alert-#{class_name} #{value}"
      .card.px-4.pt-4.pb-0.mt-3.mb-3
        .row
          .col-6.justify-content-start.d-flex.pr-0
            h2.mb-0 = "Users"
        hr
        .row
          .col-12.justify-content-start.d-flex.pr-0
          table.table.table-striped
            thead
              tr
                th scope="col"
                  = "ID"
                th scope="col"
                  = "Username"
                th scope="col"
                  = "Level"
            tbody
              - @users.each do |user|
                = render "user", user: user
          .digg_pagination.mb-3
            = will_paginate @users